/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CeylonDots {
        "animationType": string;
    }
}
declare global {
    interface HTMLCeylonDotsElement extends Components.CeylonDots, HTMLStencilElement {
    }
    var HTMLCeylonDotsElement: {
        prototype: HTMLCeylonDotsElement;
        new (): HTMLCeylonDotsElement;
    };
    interface HTMLElementTagNameMap {
        "ceylon-dots": HTMLCeylonDotsElement;
    }
}
declare namespace LocalJSX {
    interface CeylonDots {
        "animationType"?: string;
    }
    interface IntrinsicElements {
        "ceylon-dots": CeylonDots;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ceylon-dots": LocalJSX.CeylonDots & JSXBase.HTMLAttributes<HTMLCeylonDotsElement>;
        }
    }
}
